server:
  port: 8888

app:
  api-prefix: /api/v1/2025

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=3
            - id: profile_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profile/users/**
              filters:
                - StripPrefix=3